### ISSUE TITLE
Run time of Haplodup?

### ISSUE THREAD

**Issue by Dikaryotic** [andreaminio/HaploSync#1]
Heya, 

I'm having a go using the HaploSync pipeline with a guide genome for a basidiomycete fungus. The first stage, Haplosplit ran pretty fast in maybe 20 - 30 minutes, but the HaploDup stage is taking forever. At this point I've run it for at least 24 hours and it seems to be stuck on the "mapping with Gmap" stage. It timed out so I'm re-running it now with a longer wall time. The genomes about 68mb as diploid, in 1,240 or so fragments, running with 40 cores on a compute cluster with more than enough ram. Is it normal for it to take this long? 

The HaploDup_dir/ has the following files in it if that helps.
CDS.on.hap1.gmap.gff3      gmap_index.2.err         Hap1.on.Hap2.delta      Hap1_vs_Reference        Hap2.on.Hap2.err     new.CDS.fasta
CDS.on.hap1.gmap.gff3.err  gmap_index.2.log         Hap1.on.Hap2.err        Hap2.on.Hap1.coords      Hap2.on.Ref.coords      Reference_vs_Hap1
CDS.on.hap2.gmap.gff3      Hap1.on.Hap1.coords      Hap1.on.Ref.coords      Hap2.on.Hap1.coords.txt  Hap2.on.Ref.coords.txt  Reference_vs_Hap2
CDS.on.hap2.gmap.gff3.err  Hap1.on.Hap1.coords.txt  Hap1.on.Ref.coords.txt  Hap2.on.Hap1.delta       Hap2.on.Ref.delta       Ref.on.Hap2.coords
correspondence.tsv         Hap1.on.Hap1.delta       Hap1.on.Ref.delta       Hap2.on.Hap1.err         Hap2.on.Ref.err         Ref.on.Hap2.coords.txt
gmap_index                 Hap1.on.Hap1.err         Hap1.on.Ref.err         Hap2.on.Hap2.coords      Hap2_vs_Hap1            Ref.on.Hap2.delta
gmap_index.1.err           Hap1.on.Hap2.coords      Hap1_vs_Hap1            Hap2.on.Hap2.coords.txt  Hap2_vs_Hap2            Ref.on.Hap2.err
gmap_index.1.log           Hap1.on.Hap2.coords.txt  Hap1_vs_Hap2            Hap2.on.Hap2.delta       Hap2_vs_Reference       structure.tsv

**Comment by andreaminio** [comment]
Hi Chris,

Thanks for reaching out. Nope, it is not normal. GMAP runs pretty fast on such a small genome, normally. 

I see you have the gmap index folder `gmap_index` in the output, as long as the gmap result gff3 and CDS.on.hap2.gmap.gff3 CDS.on.hap1.gmap.gff3. Are they empty? 
What does the standard error say about the status? 

A.

**Comment by Dikaryotic** [comment]
The GFF3 files are not empty. The .err files show a number of "no paths found for model X" as below. 

du CDS*
204288  CDS.on.genome.gmap.gff3
133632  CDS.on.hap1.gmap.gff3
256     CDS.on.hap1.gmap.gff3.err
70912   CDS.on.hap2.gmap.gff3
768     CDS.on.hap2.gmap.gff3.err

tail CDS.on.hap2.gmap.gff3.err
No paths found for model.g996.t1
No paths found for model.g9948.t1
No paths found for model.g997.t1
No paths found for model.g998.t1
No paths found for model.g9981.t1
No paths found for model.g9980.t1
No paths found for model.g999.t1
Processed 50110 queries in 6064.93 seconds (8.26 queries/sec)
Removed existing memory for shmid 98305
Removed existing memory for shmid 65536

**Comment by andreaminio** [comment]
Hi Chris,

So I can confirm Gmap completed successfully its job. The tool is probably producing the interactive plots at that moment. in the standard error there should be a more detailed description of the process going on.
In this phase, the folders name as `Hap*_vs_*` should be populating with html, pdf and PNG files. That may take a while depending on the number of final chromosomes

Is this happening?

**Comment by Dikaryotic** [comment]
It looks like as we have been speaking it's moved from the Gmap stage to exactly what you mentioned. It has however also just error'd out with this after trying to run the script ChrBoard.pdf.nolegacy.nomarkers.R 

Traceback (most recent call last):
  File "./HaploSplit.py", line 3437, in <module>
    main()
  File "./HaploSplit.py", line 3316, in main
    refID = ref_to_hap2[queryID]
KeyError: 'SZZO02000018'

**Comment by andreaminio** [comment]
It is searching a sequence named "SZZO02000018" in the haplotype 2 file...it doesn't look much as chromosome name, but I'd need to see the HaploSplit command you used. At this stage you should also have the pseudomoelcules fasta sequences available, is "SZZO02000018" in it? Does the name say anything to you, is it an input sequence, maybe?

I see you are not using genetic markers but the reference genome to guide the assembly, right?

**Comment by andreaminio** [comment]
Sorry, My bad,

SZZO02000018 should be i the reference file...may it be an unplaced sequence?

**Comment by andreaminio** [comment]
Hold on, my bad.

SZZO02000018 is a sequence in the reference that is searched for the hap2 sequence to mach it. Does ring any bell? maybe an unplaced sequence in the FASTA?

**Comment by Dikaryotic** [comment]
Yep that's the ID of a sequence in the reference genome. From memory that will be one of the smaller sequences, and likely mitochondrial in origin. I wouldn't be surprised if it was unplaced.

**Comment by andreaminio** [comment]
So you are not using just chromosome sequence for the reference as input?

**Comment by Dikaryotic** [comment]
It's nominally a "chromosome level assembly" in about 45 scaffolds, of those about 25 appear to be genuine scaffolds with a bunch of mito debris left over. Will that be causing problems? I could tidy it up easily enough and had considered doing exactly that, but figured I'd test it as is.

**Comment by andreaminio** [comment]
Chromosome level assembly means you have sequences that are assigned 1-to-1 to chromosomes (so you can name them chr01->chXX based on the length). Do you expect to have 20 chromosomes? (45 scaffolds - 25 of "debris") They sound too many for such a basidiomycete, are you sure you don't have split arms? But even if they are arms, you should be able to do a "arm-scaled" scaffolding with the tool.

In such a case, I suggest you to use only the 20 chromosomes, as any unplaced/debris, as those are forcing the "un-placing" of sequences that may be correctly placed otherwise and, for debris, as it may be dispensable or result of a misassembly can cause issues in the phasing such of what you are seeing. What is happening is that the "debris" is not diploid in the query assembly and the second copy cannot be found (it may happen you don't find even one copy of it). 

I'll integrate a check for this situations so the error do not stop the procedure at least, but I strongly suggest not to use any small unreliable sequence for the best results.

**Comment by Dikaryotic** [comment]
Excellent, thanks for the help. That makes a lot of sense!

I've just gone and removed any of the mito scaffolds, I'm left with 24. It should be around n=12 as haploid, so yeah theyll be broken into arms.
