### ISSUE TITLE
HTML generation at end of HaploDup issue

### ISSUE THREAD

**Issue by Dikaryotic** [andreaminio/HaploSync#2]
Hi again, 

I've run through to the HaploDup stage of the workflow successfully and it says it completed. However there looks to be a few issues. The dotplots, pdf and png files are being created for each pairwise comparison, but the Hap1.on.Hap1.dotplot.png files for each set of comparisons are not being generated, which in turn looks to be messing up the final generation of the index.html file. I can go and look at individual dotplots/pdf's/pngs but none of the index's. I also don't seem to see any gene annotation files but I'm not sure if that's relevant or not sorry. 

Here is the .err output for the above file:

processing file: index.html.Rmd
output file: index.html.knit.md

File Hap1_vs_Hap1/Hap1.on.Hap1.dotplot.png not found in resource path
Error: pandoc document conversion failed with error 99
Execution halted

And the .err file for the creation of Hap1.on.Hap1.dotplot.png: 
processing file: Hap1.on.Hap1.dotplot.Rmd

Rows: 27082 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): tID, qID
dbl (8): tLen, tStart, tStop, qLen, qStart, qStop, identity, match

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Quitting from lines 16-83 (Hap1.on.Hap1.dotplot.Rmd) 
Error: Free scales cannot be mixed with a fixed aspect ratio
Backtrace:
     █
  1. ├─rmarkdown::render(...)
  2. │ └─knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3. │   └─knitr:::process_file(text, output)
  4. │     ├─base::withCallingHandlers(...)
  5. │     ├─knitr:::process_group(group)
  6. │     └─knitr:::process_group.block(group)
  7. │       └─knitr:::call_block(x)
  8. │         └─knitr:::block_exec(params)
  9. │           ├─knitr:::in_dir(...)
 10. │           └─knitr:::evaluate(...)
 11. │             └─evaluate::evaluate(...)
 12. │               └─evaluate:::evaluate_call(...)
 13. │                 ├─evaluate:::timing_fn(...)
 14. │                 ├─base:::handle(...)
 15. │                 ├─base::withCallingHandlers(...)
 16. │                 ├─base::withVisible(eval(expr, envir, enclos))
 17. │                 └─base::eval(expr, envir, enclos)
 18. │                   └─base::eval(expr, envir, enclos)
 19. └─ggplot2::ggsave(...)
 20.   ├─grid::grid.draw(plot)
 21.   └─ggplot2:::grid.draw.ggplot(plot)
 22.     ├─base::print(x)
 23.     └─ggplot2:::print.ggplot(x)
 24.       ├─ggplot2::ggplot_gtable(data)
 25.       └─ggplot2:::ggplot_gtable.ggplot_built(data)
 26.         └─layout$render(geom_grobs, data, theme, plot$labels)
 27.           └─ggplot2:::f(..., self = self)
 28.             └─self$facet$draw_panels(...)
 29.               └─ggplot2:::f(...)
Execution halted

**Comment by andreaminio** [comment]
Hi Chris,

It seems there is an issue in plotly when rendering a square shaped plot of the content... that didn't happen to me yet.
The R markdown file/code is created during the pipeline according to the data available. If you could share I may have a chance to see why it is failing.

**Comment by Dikaryotic** [comment]
Sure, what filename should I be looking for?

**Comment by andreaminio** [comment]
The file should be: `Hap1_vs_Hap1/Hap1.on.Hap1.dotplot.Rmd`
Also, can you share the version of R, plotly and ggplot2 you are using?

**Comment by Dikaryotic** [comment]
Oh, the full contents of that is what I pasted up above but I've attached it regardless.

R-base = 4.1.1 
plotly = 4.10.0
ggplot2 = 3.3.5  
[Hap1.on.Ref.dotplot.txt](https://github.com/andreaminio/HaploSync/files/7591284/Hap1.on.Ref.dotplot.txt)

**Comment by andreaminio** [comment]
I may have explained it badly, I ned the actual R markdown code that is run to produce the PNG file, that is in  `Hap1_vs_Hap1/Hap1.on.Hap1.dotplot.Rmd`, not the reported error. The specific section should be "fixed" but I have to make sure there were no issues.
also the file `Hap1.on.Hap1.coords.txt` would be useful to debug.

I see no reported issue like these online about free scales in the facets and the fixed square ration of the plot, so I fear a version compatibility issue

**Comment by andreaminio** [comment]
I was using 
- R 4.0.2 
- plotly 4.9.2.1
- ggplot2 3.3.2
and I see no error and prints the plot as expected. 

I'm checking ggplot2 code, seems an error has been added to be thrown for this combination from version 3.3.4 ...so it is not allowed anymore and probably will not be introduced back.

I'll need to find a "future-proof" workaround. T-T

A.

**Comment by Dikaryotic** [comment]
For now I've just downgraded my versions of plotly and ggplot2. Got a script/bit of code I can rerun to process just that last bit of the pipeline? It'd be nice not having to run the whole thing again is all :P

**Comment by andreaminio** [comment]
Unfortunately the indexing + the overall dotplot codes are generated automatically based on the run content (dotplots produced in runtime), so to have the full set of index and files you'll have to rerun HaploSplit
The actual production of the plots is the one that takes 90% of the time, so restarting it from scratch or only producing the dotplots has very small impact on the timing. However, in the standard error, the tool reports the exact command used to produce each R plot, so if you run 
`grep -F "Hap1.on.Hap1.dotplot.Rmd" ${output}.err`
you'll get the command line that produces `Hap1.on.Hap1.dotplot.{html,pdf,png}`, it's worth a try to see if the library combination works.

**Comment by andreaminio** [comment]
I modified the R code for the dotplot production. 
Now it makes no use of the facets and it will be interactive (html file of the index will be a little bigger though :-D ) and there should be no compatibility issue in any ggplot2 or plotly version
