### ISSUE TITLE
Installation Issue 

### ISSUE THREAD

**Issue by AnnieHonnet** [andreaminio/HaploSync#6]
Hi AndreaMinio, 

Thank you for creating HaploSync. I am in the process of assembling and annotating a de novo diploid genome and quite interesting in using HaploSync to improve my assembly. However, I have so a bit trouble installing the program using miniconda2 on LinuxMint. 
If would froze after awhile. 

Any suggestion would be appreciated!
Thanks 

Annie Nguyen

**Comment by noecochetel** [comment]
The installation instructions were updated, the use of miniconda3 should solve any freezing issues.
